# Generated by Django 5.2.8 on 2025-11-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_create_savingsgoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsgoal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
