# Generated by Django 5.2.8 on 2025-11-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_savingsgoal_id'),
        ('finance', '0004_transaction_budget'),
    ]

    operations = [
    ]
